SELECT `PAGES_TYPE_MAVIE`.`ID`, `PAGES_TYPE_MAVIE`.`SUBTITLE`, `PAGES_TYPE_MAVIE`.`IMG_SRC`, `PAGES_TYPE_MAVIE`.`TYPE`, `PAGES_TYPE_MAVIE`.`TITLE` FROM `PAGES_TYPE_MAVIE` 
INNER JOIN `PAGES_MAVIE` ON `PAGES_TYPE_MAVIE`.`ID` = `PAGES_MAVIE`.`ID_PAGE_TYPE`
WHERE `PAGES_MAVIE`.`ID` = %ID%