SELECT `PAGES_TYPE`.`ID`, `PAGES_TYPE`.`SUBTITLE`, `PAGES_TYPE`.`IMG_SRC`, `PAGES_TYPE`.`TYPE`, `PAGES_TYPE`.`TITLE` FROM `PAGES_TYPE_MAVIE` 
INNER JOIN `PAGES_MAVIE` ON `PAGES_TYPE`.`ID` = `PAGES`.`ID_PAGE_TYPE`
WHERE `PAGES`.`ID` = %ID%